<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="ni3-hao3-qwer"><a href="#ni3-hao3-qwer">你好，QWER！</a></h2>
    <p>这是一篇使用简体中文编写的测试文章。</p>
    <h3 id="wei4-shen2-me-hui4-kan4-dao4-luan4-ma3">
      <a href="#wei4-shen2-me-hui4-kan4-dao4-luan4-ma3">为什么会看到“乱码”？</a>
    </h3>
    <p>
      在示例文章 <code class="inline-code-block">Hello QWER 👋</code>
       中，为了展示多语言支持，作者列出了几十种语言的“你好世界”。其中包含：
    </p>
    <ul>
      <li>阿拉伯语：مرحبا بالعالم!</li>
      <li>埃塞俄比亚语：ሰላም ልዑል!</li>
      <li>印地语：नमस्ते दुनिया!</li>
    </ul>
    <p>这些并不是真正的乱码，而是不同国家的文字。因为有些文字看起来很不寻常，所以可能会被误认为是乱码。</p>
    <h3 id="zhen1-zheng4-de-jian3-ti3-zhong1-wen2-xian3-shi4">
      <a href="#zhen1-zheng4-de-jian3-ti3-zhong1-wen2-xian3-shi4">真正的简体中文显示</a>
    </h3>
    <p>如你所见，这篇文章的所有中文内容都能正常显示，没有任何编码问题。</p>
    <ul>
      <li><strong>粗体文字</strong></li>
      <li><em>斜体文字</em></li>
      <li><a href="https://www.baidu.com" rel="external">链接到百度</a></li>
    </ul>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-python">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"你好，世界！"</span><span class="token punctuation">)</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
  </article>
</Post>
